import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import authRoutes from './routes/auth.js';
const app=express();
app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173'})); app.use(express.json());
app.get('/api/health',(req,res)=>res.json({ok:true,service:'Vani API'}));
app.use('/api/auth',authRoutes);
const port=process.env.PORT||5000;
mongoose.connect(process.env.MONGO_URI).then(()=>app.listen(port,()=>console.log(`Vani API running on ${port}`))).catch(e=>{console.error('MongoDB connection failed:',e.message);process.exit(1)});
